/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappParaPetshopRouteImport } from './routes/whatsapp-para-petshop'
import { Route as ValeAPenaRouteImport } from './routes/vale-a-pena'
import { Route as TechRouteImport } from './routes/tech'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SistemaParaPetshopRouteImport } from './routes/sistema-para-petshop'
import { Route as SistemaBanhoETosaRouteImport } from './routes/sistema-banho-e-tosa'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as EcossistemaRouteImport } from './routes/ecossistema'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CareRouteImport } from './routes/care'
import { Route as AssinarRouteImport } from './routes/assinar'
import { Route as IndexRouteImport } from './routes/index'

const WhatsappParaPetshopRoute = WhatsappParaPetshopRouteImport.update({
  id: '/whatsapp-para-petshop',
  path: '/whatsapp-para-petshop',
  getParentRoute: () => rootRouteImport,
} as any)
const ValeAPenaRoute = ValeAPenaRouteImport.update({
  id: '/vale-a-pena',
  path: '/vale-a-pena',
  getParentRoute: () => rootRouteImport,
} as any)
const TechRoute = TechRouteImport.update({
  id: '/tech',
  path: '/tech',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaParaPetshopRoute = SistemaParaPetshopRouteImport.update({
  id: '/sistema-para-petshop',
  path: '/sistema-para-petshop',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaBanhoETosaRoute = SistemaBanhoETosaRouteImport.update({
  id: '/sistema-banho-e-tosa',
  path: '/sistema-banho-e-tosa',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const EcossistemaRoute = EcossistemaRouteImport.update({
  id: '/ecossistema',
  path: '/ecossistema',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarRoute = AssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRoute
  '/care': typeof CareRoute
  '/contato': typeof ContatoRoute
  '/ecossistema': typeof EcossistemaRoute
  '/planos': typeof PlanosRoute
  '/sistema-banho-e-tosa': typeof SistemaBanhoETosaRoute
  '/sistema-para-petshop': typeof SistemaParaPetshopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/tech': typeof TechRoute
  '/vale-a-pena': typeof ValeAPenaRoute
  '/whatsapp-para-petshop': typeof WhatsappParaPetshopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRoute
  '/care': typeof CareRoute
  '/contato': typeof ContatoRoute
  '/ecossistema': typeof EcossistemaRoute
  '/planos': typeof PlanosRoute
  '/sistema-banho-e-tosa': typeof SistemaBanhoETosaRoute
  '/sistema-para-petshop': typeof SistemaParaPetshopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/tech': typeof TechRoute
  '/vale-a-pena': typeof ValeAPenaRoute
  '/whatsapp-para-petshop': typeof WhatsappParaPetshopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRoute
  '/care': typeof CareRoute
  '/contato': typeof ContatoRoute
  '/ecossistema': typeof EcossistemaRoute
  '/planos': typeof PlanosRoute
  '/sistema-banho-e-tosa': typeof SistemaBanhoETosaRoute
  '/sistema-para-petshop': typeof SistemaParaPetshopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/tech': typeof TechRoute
  '/vale-a-pena': typeof ValeAPenaRoute
  '/whatsapp-para-petshop': typeof WhatsappParaPetshopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assinar'
    | '/care'
    | '/contato'
    | '/ecossistema'
    | '/planos'
    | '/sistema-banho-e-tosa'
    | '/sistema-para-petshop'
    | '/sitemap.xml'
    | '/sobre'
    | '/tech'
    | '/vale-a-pena'
    | '/whatsapp-para-petshop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assinar'
    | '/care'
    | '/contato'
    | '/ecossistema'
    | '/planos'
    | '/sistema-banho-e-tosa'
    | '/sistema-para-petshop'
    | '/sitemap.xml'
    | '/sobre'
    | '/tech'
    | '/vale-a-pena'
    | '/whatsapp-para-petshop'
  id:
    | '__root__'
    | '/'
    | '/assinar'
    | '/care'
    | '/contato'
    | '/ecossistema'
    | '/planos'
    | '/sistema-banho-e-tosa'
    | '/sistema-para-petshop'
    | '/sitemap.xml'
    | '/sobre'
    | '/tech'
    | '/vale-a-pena'
    | '/whatsapp-para-petshop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssinarRoute: typeof AssinarRoute
  CareRoute: typeof CareRoute
  ContatoRoute: typeof ContatoRoute
  EcossistemaRoute: typeof EcossistemaRoute
  PlanosRoute: typeof PlanosRoute
  SistemaBanhoETosaRoute: typeof SistemaBanhoETosaRoute
  SistemaParaPetshopRoute: typeof SistemaParaPetshopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TechRoute: typeof TechRoute
  ValeAPenaRoute: typeof ValeAPenaRoute
  WhatsappParaPetshopRoute: typeof WhatsappParaPetshopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp-para-petshop': {
      id: '/whatsapp-para-petshop'
      path: '/whatsapp-para-petshop'
      fullPath: '/whatsapp-para-petshop'
      preLoaderRoute: typeof WhatsappParaPetshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vale-a-pena': {
      id: '/vale-a-pena'
      path: '/vale-a-pena'
      fullPath: '/vale-a-pena'
      preLoaderRoute: typeof ValeAPenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech': {
      id: '/tech'
      path: '/tech'
      fullPath: '/tech'
      preLoaderRoute: typeof TechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema-para-petshop': {
      id: '/sistema-para-petshop'
      path: '/sistema-para-petshop'
      fullPath: '/sistema-para-petshop'
      preLoaderRoute: typeof SistemaParaPetshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema-banho-e-tosa': {
      id: '/sistema-banho-e-tosa'
      path: '/sistema-banho-e-tosa'
      fullPath: '/sistema-banho-e-tosa'
      preLoaderRoute: typeof SistemaBanhoETosaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecossistema': {
      id: '/ecossistema'
      path: '/ecossistema'
      fullPath: '/ecossistema'
      preLoaderRoute: typeof EcossistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar': {
      id: '/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AssinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssinarRoute: AssinarRoute,
  CareRoute: CareRoute,
  ContatoRoute: ContatoRoute,
  EcossistemaRoute: EcossistemaRoute,
  PlanosRoute: PlanosRoute,
  SistemaBanhoETosaRoute: SistemaBanhoETosaRoute,
  SistemaParaPetshopRoute: SistemaParaPetshopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TechRoute: TechRoute,
  ValeAPenaRoute: ValeAPenaRoute,
  WhatsappParaPetshopRoute: WhatsappParaPetshopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
